# Generated by Django 5.0.6 on 2024-05-27 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeatitudoMediaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(unique=True)),
                ('nickname', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LovedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('beatitudo_media_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loved_article', to='beatitudomediausers.beatitudomediauser')),
            ],
        ),
        migrations.CreateModel(
            name='ViewedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.IntegerField()),
                ('beatitudo_media_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_article', to='beatitudomediausers.beatitudomediauser')),
            ],
        ),
    ]
