# Generated by Django 5.0.6 on 2024-05-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_sections_article_section_alter_section_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
