# Generated by Django 5.0.6 on 2024-05-12 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0008_alter_article_metadata_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.section'),
        ),
        migrations.AlterField(
            model_name='article_auxiliary_data',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.article'),
        ),
        migrations.AlterField(
            model_name='section',
            name='sections',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sections.sections'),
        ),
    ]
