# Generated by Django 5.0.6 on 2024-05-17 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0012_remove_section_sections_alter_article_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_views',
        ),
        migrations.AddField(
            model_name='article_metadata',
            name='article_views',
            field=models.IntegerField(default=0),
        ),
    ]
