# Generated by Django 5.0.6 on 2024-05-23 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0014_rename_article_auxiliary_data_articleauxiliarydata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='sections.section'),
        ),
    ]
