# Generated by Django 5.0.6 on 2024-06-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.TextField()),
                ('title', models.TextField()),
                ('thumbnail_url', models.TextField()),
                ('article_url', models.TextField()),
            ],
        ),
    ]
