# Generated by Django 5.0.6 on 2024-06-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatitudomediawebservices', '0002_processedarticle_time_to_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedarticle',
            name='date',
            field=models.TextField(default=''),
        ),
    ]
