# Generated by Django 5.0.6 on 2024-05-11 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sections.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='section',
            name='sections',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sections.sections'),
        ),
    ]
