# Generated by Django 5.0.6 on 2024-05-12 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0005_alter_section_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_auxiliary_data_url',
        ),
        migrations.RemoveField(
            model_name='article',
            name='article_metadata_url',
        ),
        migrations.AddField(
            model_name='article_auxiliary_data',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sections.article'),
        ),
        migrations.AddField(
            model_name='article_metadata',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sections.article'),
        ),
    ]
