# Generated by Django 5.0.6 on 2024-05-12 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0006_remove_article_article_auxiliary_data_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article_auxiliary_data',
            name='loved',
        ),
        migrations.RemoveField(
            model_name='sections',
            name='description',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article_auxiliary_data',
            name='count_of_loved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article_auxiliary_data',
            name='count_of_shared',
            field=models.IntegerField(default=0),
        ),
    ]
