# Generated by Django 5.0.6 on 2024-05-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_p'),
    ]

    operations = [
        migrations.DeleteModel(
            name='P',
        ),
    ]
